#!/bin/sh

profile_name="$(ls "${XDG_CONFIG_HOME:-$HOME/.config}"/work_profiles | dmenu -p "select a profile")"
profile_path="${XDG_CONFIG_HOME:-$HOME/.config}/work_profiles/$profile_name"

[ ! -d "$profile_path" ] && notify-send "profile \"$profile_path\" is not a valid profile directory" && exit 1

if [ -f "$profile_path/lock" ]; then
    [ -x "$profile_path/stop" ] && "$profile_path/stop"
    kill -9 $(cat "$profile_path/lock" | sed '1q;d') && notify-send "session stopped" || notify-send "the session was not running"
    start=$(cat "$profile_path/lock" | sed '2q;d')
    end=$(date +%s)

    working_time=$(((end - start) / 60))

    echo "e$(date -d @"$end")" >> "$profile_path/times_start_end"
    echo "$working_time minutes ($(date -d @"$start") to $(date -d @"$end"))" >> "$profile_path/$(hostname)_times"
    cp "$profile_path/$(hostname)_times" "$profile_path/.$(hostname)_times.bak"

    notify-send "DONE!" "you've been working for $working_time minutes" || notify-send "Oops" "the profile has exited with an error code"

    "$profile_path/save" $working_time
    rm "$profile_path/lock"
    pkill -RTMIN+7 blocks # update icon
    exit
fi

[ ! -x "$profile_path/run" ] && notify-send "could not run this profile" "the file do not exist or is not executable" && exit 1

start=$(date +%s)
echo "s$(date -d @"$start")" >> "$profile_path/times_start_end"

st -t "work_profile" -e sh "$profile_path/run" &
pid=$!
printf "%s\n%s" "$pid" "$start" > "$profile_path/lock"
pkill -RTMIN+7 blocks # update icon

notify-send -u low "Started profile $profile_name" "pid: $pid"
