#!/bin/sh

working_time="$1"
[ -n "$working_time"] && notify-send -u warning "no working time measured"
message="$(ls messages | dmenu -p "what were you doing today?")"
echo "$working_time minutes ($(date -d @"$start") to $(date -d @"$end")) $message" >> times

here="$(pwd)"

if [ -n "$message" ]; then
    cd "$HOME/work/systail_panel/front"
    git add .
    git commit -m "$message" > "$here/commit.log"
    notify-send -u normal "commiting changes" "$(cat "$here/commit.log")"
    cd $here

    response="$(printf "yes\nno" | dmenu -p "push changes")"
    case "$response" in
        [yY][eE][sS]|[yY])
            # echo "pushing..."
            notify-send -u low "pushing changes"
            
            cd "$HOME/work/systail_panel/front"
            git push --porcelain --verbose > "$here/push.log" 2>"$here/push.err.log" && notify-send -u low "done" || notify-send -u critical "could not push changes" "see $here/push.err.log"
            cd $here
            ;;
    esac
fi