#!/bin/sh

#cd "$HOME"/work/systail_panel
#./run_dev
# [ ! $(sudo systemctl is-active --quiet docker.service) ] && sudo systemctl start docker.service

# docker-compose up && notify-send -u low "stopped docker container" || notify-send -u critical "docker compose failed"
