#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
setbg &			# set the background with the `setbg` script
#slock &
#xwinwrap -b -fs -sp -fs -nf -ov  -- /usr/lib/xscreensaver/deepstars -root -window-id WID &
eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg)
xrdb "${XDG_CONFIG_HOME:-$HOME/.config}"/Xresources
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY
# screens=$(xrandr -q | grep " connected" | awk '{print $1}' | sort)
# primary=$(echo $screens | tr -s '\n' ' ' | cut -d ' ' -f1)
# for s in "$(echo ${screens##$primary} | xargs)"; do
# 	args="$args --output $primary --auto --output $s --right-of $primary --auto"
# 	primary=$s
# done
#
# eval xrandr $args

setxkbmap pl		# support polish chars
mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
xcompmgr &		# xcompmgr for transparency
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
pidof redshift >/dev/null && killall redshift
redshift 2>&1 >/dev/null &
#killall syncthing 2>/dev/null
#syncthing -no-browser 2>&1 >/dev/null &
