[theme]
background = "#191919"
primary = "#AEAEAE"
secondary = "#DCDCDC"
title = "#FFFFFF"
playing = "#547756"
playing_selected = "#1BAB4E"
playing_bg = "#000000"
highlight = "#FDFDFF"
highlight_bg = "#3F757F"
error = "#FFE4E4"
error_bg = "#C94343"
statusbar = "#FFFFFF"
statusbar_progress = "#77B3D1"
statusbar_bg = "#445CB1"
cmdline = "#CBFFDE"
cmdline_bg = "#21C4BA"
